#!/bin/bash
# By default, xmonad looks for this in ~/.xmonad/xmonad-session-rc.
# If this file does not exist, create it, or a link to this content.

# Deal with default multi-monitor config
# Set awk Output Record Separator to one space, since records are separated by \n by
# default (unlike fields).
ALL_MONITORS_STR=$(xrandr --current | grep " connected " | awk 'BEGIN { ORS = " "}; {print $1}' )
read -r -a ALL_MONITORS <<< "$ALL_MONITORS_STR"
NB_CONNECT_OUTPUT="${#ALL_MONITORS[@]}"

# Path is not set yet, and sourcing ~/.bashrc does not seem to work.
PATH=~/bin:$PATH

if [ $NB_CONNECT_OUTPUT == 3 ] ; then
    echo "Docking on login" >> /tmp/xmonad.log
    dock
else
    echo "Undocking on login" >> /tmp/xmonad.log
    undock
fi

GTK_THEME=Equilux-compact
export GTK_THEME

GTK2_RC_FILES=/usr/share/themes/Equilux-compact/gtk-2.0/gtkrc
export GTK2_RC_FILES

# Compositor
if [[ -x "/usr/bin/compton" ]]; then
    compton --config "$HOME/.xmonad/compton.conf" &
fi

# Tray for skype and other icons
# Nowadays dealing with trayer on user request only, see xmonad.hs. Even using xfce4-panel.
#trayer --edge top --align right --SetDockType true --SetPartialStrut true  --expand true --widthtype request --transparent true --alpha 0 --tint 0x333333 --height 16 --monitor 0 &

# Keyboard layout switcher
#if [[ -f $HOME/kinesis/kinesis_swe_us.conf ]]; then
#    # See https://github.com/fleutot/kinesis
#    #xkbcomp -i 3 $HOME/kinesis/kinesis_swe_us.conf $DISPLAY
#    # The commented row above did not work at startup. Maybe $DISPLAY cannot be used too early?
#    xkbcomp -i 3 $HOME/kinesis/kinesis_swe_us.conf :0
#else
#    # alt_shift_toggle stopped working (switching on press instead of release, breaking shortcuts with alt+shift).
#    # alt_caps might be better anyway, preventing rogue presses in eg emacs (M-< and M->).
#    #setxkbmap -layout us,us,se -variant ,dvp, -option 'grp:alt_caps_toggle' &
    setxkbmap -layout us,se -option 'grp:alt_caps_toggle'
#fi

# Per window keyboard layout
kbdd

# Java applications don't detect xmonad as a non-reparenting WM, resulting in grey empty windows.
# (under investigation, this might have to move to ~/.bashrc)
#Trying to do that in xmonad.hs, check after restart and remove this if setting
# from xmonad.hs worked.
# Now not done in xmonad.hs since upgrade, yet Cooja is happy. Java detects
# non-reparenting automatically, maybe? Or xmonad sets it by itself?
#export _JAVA_AWT_WM_NONREPARENTING=1

# Startup apps

if type xscreensaver ; then
    xscreensaver -nosplash &
fi

if type dropbox ; then
    dropbox start
fi

if type emacs ; then
    emacs &
fi

if type gnome-terminal ; then
    gnome-terminal &
fi

if type gnome-power-manager ; then
    sleep 3
    gnome-power-manager &
elif type xfce4-power-manager ; then
    sleep 2
    # This might require superuser in order to allow hibernate.
    xfce4-power-manager &
fi

if type unclutter ; then
    # unclutter starts a default version by itself, see (and modify)
    # /etc/default/unclutter
    # -noevents is needed in order not to give focus to the window under the
    # possibly hidden cursor upon switching workspace.  Try without -grab to let
    # xscreensaver use the mouse, and lock faster (otherwise it tries and fails
    # to grab the mouse pointer, and times out).  -grab was added earlier to
    # "avoid erroneous focus changes", let's test and see.
    # First try to run unclutter from apt. If it doesn't work (-noevents not
    # supported), try the other one.
    unclutter -noevents &

    if ! pgrep unclutter ; then
        # --ignore-scrolling doesn't seem to work.
        unclutter --timeout 1 --ignore-scrolling&
    fi
fi

if type nm-applet ; then
    nm-applet &
fi

# Make ssh-agent prompt for key passphrase once and for all.
# Problem: this does not seem to prompt for password, can it really be run from this file?
ssh-add
