#!/bin/bash
# By default, xmonad looks for this in ~/.xmonad/xmonad-session-rc.
# If this file does not exist, create it, or a link to this content.

# Deal with default multi-monitor config
# Set awk Output Record Separator to one space, since records are separated by \n by
# default (unlike fields).
ALL_MONITORS_STR=$(xrandr --current | grep " connected " | awk 'BEGIN { ORS = " "}; {print $1}' )
read -r -a ALL_MONITORS <<< "$ALL_MONITORS_STR"
NB_CONNECT_OUTPUT="${#ALL_MONITORS[@]}"
MONITOR_LAPTOP=${ALL_MONITORS[0]}
MONITOR_LEFT=${ALL_MONITORS[1]}
MONITOR_RIGHT=${ALL_MONITORS[2]}
if [ $NB_CONNECT_OUTPUT == 3 ] ; then
    xrandr \
        --output $MONITOR_LEFT --pos 0x0 --auto --primary \
        --output $MONITOR_RIGHT --right-of $MONITOR_LEFT --auto \
        --output $MONITOR_LAPTOP --auto --pos 960x1200
fi

# Compositor
if [[ -x "/usr/bin/compton" ]]; then
    compton --config "$HOME/.xmonad/compton.conf" &
fi

# Wallpaper
# To randomly switch wallpaper every hour, add a crontab:
# env | grep -i display # get the name of the current display, e.g. DISPLAY=:0.0
# crontab -e
# 0 *    *   *   *     DISPLAY=:0.0 feh --bg-fill $(find /opt/gauthier/Pictures/wallpapers -type f |sort -R |head -1)
if type wallpaper_random_set.sh ; then
    $HOME/bin/wallpaper_random_set.sh
elif [[ -f "$HOME/wallpaper.jpg" ]] && hash feh ; then
    feh --bg-fill "$HOME/wallpaper.jpg"
fi

# Tray for skype and other icons
trayer --edge top --align right --SetDockType true --SetPartialStrut true  --expand true --widthtype request --transparent true --alpha 0 --tint 0x333333 --height 16 --monitor 0 &

# Keyboard layout switcher
if [[ -f $HOME/kinesis/kinesis_swe_us.conf ]]; then
    # See https://github.com/fleutot/kinesis
    xkbcomp -i 3 $HOME/kinesis/kinesis_swe_us.conf $DISPLAY
else
    # alt_shift_toggle stopped working (switching on press instead of release, breaking shortcuts with alt+shift).
    # alt_caps might be better anyway, preventing rogue presses in eg emacs (M-< and M->).
    #setxkbmap -layout us,us,se -variant ,dvp, -option 'grp:alt_caps_toggle' &
    setxkbmap -layout us,se -option 'grp:alt_caps_toggle'
fi

# Per window keyboard layout
kbdd

# Java applications don't detect xmonad as a non-reparenting WM, resulting in grey empty windows.
# (under investigation, this might have to move to ~/.bashrc)
#Trying to do that in xmonad.hs, check after restart and remove this if setting from xmonad.hs worked.
#export _JAVA_AWT_WM_NONREPARENTING=1

# Startup apps

if type xscreensaver ; then
    xscreensaver -nosplash &
fi

if type dropbox ; then
    dropbox start
fi

if type emacs ; then
    emacs &
fi

if type gnome-terminal ; then
    gnome-terminal &
fi

if type gnome-power-manager ; then
    sleep 3
    gnome-power-manager &
elif type xfce4-power-manager ; then
    sleep 2
    # This might require superuser in order to allow hibernate.
    sudo xfce4-power-manager &
fi

# if [[ -x "/opt/thefanclub/grive-tools/grive-indicator" ]] ; then
#     /opt/thefanclub/grive-tools/grive-indicator &
# fi

if type unclutter ; then
    # unclutter starts a default version by itself, see (and modify) /etc/default/unclutter
    # -noevents is needed in order not to give focus to the window under the
    # possibly hidden cursor upon switching workspace.
    # Try without -grab to let xscreensaver use the mouse, and lock faster (otherwise it tries
    # and fails to grab the mouse pointer, and times out).
    # -grab was added earlier to "avoid erroneous focus changes", let's test and see.
    unclutter -noevents &
fi

nm-applet &

# Hipchat client not working, some troubles with QT. Use Franz instead
# if type hipchat4 ; then
#     hipchat4 &
# fi

if type franz ; then
    franz &
fi

# Testing this syntax, to be continued...
if type gnome-pomodoro ; then
    gnome-pomodoro &
fi
